spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 58859476
    url: jdbc:mysql://localhost:3306/umc_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000